apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.ConfigMaps.InitConfig.name }}
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: {{ .Values.ConfigMaps.komposeServiceLabel }}
data:
  init.sh: |
    {{ .Values.ConfigMaps.InitConfig.initScript | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.ConfigMaps.DatasetConfig.name }}
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: {{ .Values.ConfigMaps.komposeServiceLabel }}
data:
  Dataset.json: |
    {{ .Values.ConfigMaps.DatasetConfig.Dataset | nindent 4 }}
