apiVersion: v1
data:
  config.json: |
    {
        "directMongoAccess": true,
        "doiBaseUrl": "http://landingpage.localhost/detail/",
        "facility": "facility",
        "scicatBaseUrl": "${FRONTEND_URL}",
        "lbBaseUrl": "${BACKEND_URL}"
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: landingpage
  name: landingpage-cm0
