apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    io.kompose.service: backend
spec:
  selector:
    io.kompose.service: backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP # This can be LoadBalancer
