apiVersion: v1
kind: Service
metadata:
  name: landingpage-service
  labels:
    io.kompose.service: landingpage
spec:
  selector:
    io.kompose.service: landingpage
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
