services:
  api_scripts:
    image: bermudea/myscicatlive_api_scripts:1.0
    container_name: myscicat_api_scripts
    volumes:
      - ${PWD}/data:/app/data
      - ${PWD}/entrypoints/infinite_loop.sh:/app/infinite_loop.sh
    entrypoint:
      - /app/infinite_loop.sh
      - /app/entrypoint.sh
